name: KeepAlive
on: 
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Check out code 
        uses: actions/checkout@v3
      
      - uses: nanasess/setup-chromedriver@v2
      
      - run: |
          pip3 install -q selenium==4.9.0
          python3 ./keepalive.py
