name: Open Website

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  open_website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Open website
        run: |
          npm run open-website
