name: Tor Selenium Action

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  browse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install tor
        pip install seleniumbase

    - name: Visit the website using SeleniumBase and Tor
      run: |
        tor &
        git clone https://github.com/seleniumbase/SeleniumBase.git
        cd SeleniumBase/examples/
        echo 'from seleniumbase import BaseCase
        import time
        class MyTestClass(BaseCase):
            def test_tor_browser(self):
                self.open("https://ide-run.goorm.io/workspace/dO8D4ys44ocxrovRqIA?token=0312731cf35a27ab2f073e3553c775dc&guestname=13")
                time.sleep(60)
        ' > tor_test.py
        pytest tor_test.py
