name: Visit Goormio Page

on:
  schedule:
    # Runs every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch:
    # Allows you to manually trigger the action

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install seleniumbase

    - name: Visit the page
      run: |
        echo "Setting up tor..."
        sudo apt-get install tor
        sudo service tor start

        echo "Running selenium script..."
        python goorm.py
