name: Open website
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  open-website:
    runs-on: ubuntu-latest
    steps:
      - name: Open website
        uses: actions/shell@v2
        with:
          args: |
            xdg-open https://ide-run.goorm.io/workspace/d9Sssb0cUEnisCoRCgX?token=d04702b4519674ab9a512f72b1bae53d&guestname=12
            sleep 60
